### ISSUE TITLE
Milestone2 adlı docx dokümanına bakınız

### ISSUE THREAD

**Issue by MelisaSarici** [MelisaSarici/GaN-FET#10]
@furkankarakaya @mesutto 

İkinci milestone'a da baktım. GaN için diode olmayacak onun yerine capacitor ile ilgili bir loss hesabı lazım. Ancak bu durumu tam kavrayamadım. Capacitorleri daha iyi anlamak adına onGaN adlı klasörde TI in MOSFET leri anlattığı dokümana tekrar göz attım ve aklıma gelen tüm soruları Milestone2 adlı docx dokümanına yazdım. Özellikle aklıma takılan nokta:biz outputta bir sinüs görmüyoruz değil mi? Fundamental componentı istediğimiz sinüsü taşıyan farklı on off sürelerine sahip bir kare dalga topluluğu aslında? Çünkü power hesabı yaparken voltajımı neye göre alacağımda kafam karıştı. Perfect sinüs gibi mi bu kare dalgaları baz alarak mı?

**Comment by furkankarakaya** [comment]
Bahsettiğin dokümanı bulamadım, senin GaN-FET repona ve Drive'da IMMD Research klasörüne baktım. Farklı bir yerde mi?
