### ISSUE TITLE
Simscape Model

### ISSUE THREAD

**Issue by MelisaSarici** [MelisaSarici/GaN-FET#2]
What I see: @furkankarakaya 

Simscape SPICE Comaptible MOS model has some useful features like all parameters from the width, length of the device to the thermal elements. So can not we use it for MOS and GaN?

I did not arrange anything specifically, I just wanted to see whether this SPICE MOS gives a logical output as Simscape MOS does. But no, it gives a spike. Maybe more can be seen when some realistic parameter values are entered. I did not do this since there are a lot. It would be nice to have some advice.

**Comment by furkankarakaya** [comment]
Hi Melisa,
For a detailed discussion, could you please follow the issue that I just started under IMMD repository.

Excuse me, I couldn't get your question. Can you share the .slx file or the results? Thanks :)

**Comment by MelisaSarici** [comment]
@furkankarakaya 
.slx file is the already existent last model. I changed and commited. Isn't it visible?

**Comment by furkankarakaya** [comment]
Maybe you committed but not pushed? It seems it was 8 days ago,  the last commit.

**Comment by ozank** [comment]
Sorun çözüldü mü arkadaşlar? :stuck_out_tongue:

**Comment by MelisaSarici** [comment]
Çözdük hocam. ^_^

22 Eki 2017 23:45 tarihinde "Ozan K" <notifications@github.com> yazdı:
