### ISSUE TITLE
Loss Modelleme hedefler

### ISSUE THREAD

**Issue by MelisaSarici** [MelisaSarici/GaN-FET#3]
@mesutto 

Burdan sorularımı yazsam daha güzel olabilir, commitimle aynı:

İki gün süresince inverter üzerine Mohandan çalışıyorum. Konu bira genişçe olduğu için single phase den başlamam gerekti. Hatta 463 derste Ozan Hoca'nın en son işlediği 3 faz, tek faz rectifier konusunu da tekrar ederek bu konseptlerdeki bakış açımı iyice oturtmaya çalıştım. Ama sanıyorum ki inverter konusu kavradım. 3 faz henüz tam bitmedi ve blanking time 8.5 başlığındayım. Şimdiye dek sormak istediğim birkaç ana başlık var:

[]There are different methods for pwm switching. Are we going to use bipolar, unipolar or square? In square wave operation, it is stated that for larger frequency modulation constant (m_f) there wil be more harmonics (obviously for larger frequencies can be filtered) yet these harmonics will introduce more ripples. So what is with that? Can this be filtered? Or are we using bipolar or unipolar?

[]Will the operation be overmodulated or linear modulated?

[]What will be the frequency operation and m_f? Will it be synchronized PWM eliminating even harmonics or for hih frequencies we wont care?

So these are the points appearing during reading the inverters.

**Comment by furkankarakaya** [comment]
Melisa merhaba, issue'yu yeni görüyorum @mesutto yoğun olduğu için ben kısaca cevaplamaya çalışayım.
 1) PWM anahtarlamalarının mantığını zannediyorum anlamışsındır, iki farklı dalgayı karşılaştırarak ona göre anahtarlara sinyal gönderiliyor. Bu konsepti daha iyi yakalamak için aşağıdaki linki izleyebilirsin.
https://www.youtube.com/watch?v=qVeERT4nyz8
Onun dışında anahtarlama yöntemine göre üretilen harmonikler değişiklik gösteriyor. Örneğin, square wave inverterlar için harmonikler Mohan'da Figure 8-24'de verilmiş. Fark ettiysen harmonikler kare dalgaya benziyor ama 3 faz olduğu için 3'ün katlarını göremiyoruz. Bunun yarattığı problem aslında şu eğer sistemdeki harmonikler fundamental frekansdan çok yüksek olsaydı bir low-pass filtre ile harmoniklerden kurtulmak çok kolaylaşırdı. Ama square-wave inverter konseptinde fundamentaldan sonra gelen harmonik, 5. harmonik olduğu için ve diğer harmoniklerde yakın devam ettiği için bunları filtrelemek, etkilerini azaltmak zorlaşıyor. Dolayısı ile bu harmoniklerin varlığı çıkış kaliteni düşürüyor.
Şu an hangi PWM tekniğini kullanacağımız net değil sanırım çünkü bu konununda detayları var belki kısaca harmonic injection diye aratıp bakabilirsin. Bu konuyla ilgili de bir arkadaş çalışıyor.
İlk soruna ikinci soruyu da katarak devam edelim. Mohan'daki Figure 8-23'te belirtildiği üzere ma ,yani gate sinyallerini oluştururken kullandığın sinüs dalgasının amplitude değerinin üçgen dalganın amplitude değerine oranı, arttıkça kareleşen bir operasyona dönüşecek ve harmonikler kötüleşecek. Yani overmodule bir inverter'ın çıkış harmonikleri lineer module inverter'dan daha kötüdür. Lakin output amplitude'unu arttırmak istediğin durumlarda over module bölgeye yaklaşman gerekebilir, bunun içinde lineer bölgede kalıp yüksek output gerilimi elde etmek için yöntemler var(harmonic injection).
İlk sorundaki frequency modulation ile square wave operation'unun bağlantısını bilmiyorum, benim bildiğim kadarıyla, Mohan'da da böyle yazıyor(Ch. 8-4-2), square wave operation harmonikleri 6n+-1 oluyor. Dolayısı ile square wave operation harmonikleri ve mf arasında bir bağlantı yok diye biliyorum ki zaten square wave operation için mf tanımlı olmamalı.

3) Synchronized PWM'i hatırlayamadım, biraz incelemem lazım.

Umarım işine yarar birşeyler yazmışımdır :)
