### ISSUE TITLE
Son komitim(:D) Soruları buraya taşımak adına

### ISSUE THREAD

**Issue by MelisaSarici** [MelisaSarici/GaN-FET#4]
@mesutto 

3 faz inverterde öncelikle sampling time sorunu üzerine çalıştım. Düzgün output elde edebilmek için configuration parametrelerindeki ve üçgen dalgada kullanılan sampling aynı olmalı ve powerguide kullanılan sampling time dan kesinlikle küçük olmalı(ben 100 kat kullandım, bu süreyi biraz büyütüyor ancak aksi durumda switcingdeki rising time o kadar uzun oluyor ki kare değil üçgen görmeye başlıyoruz)

İkincisi Matlab'da yazdığım deperlerle oynayarak, mf ve ma belirledim, hangi mf değerlerinde nasıl fft gördüğümü inceledim. Bulgularım şu yönde, eğer mf aşırı büyük olursa overmodulationa benzer bir fft dağılımı oluyor, yani switcing frekansı etrafında görülen katkı spektruma bayağı yayılıyor. Ancak burada düzgün veri alamamın sebebi zannediyorum ki sampling time ı o kadar düşürememem (1 cycle i tamamlaması 15-20dk alabilir.) de olabilir. Bu nokta aslında sormak istediğim bir şey, mf nin çok büyük olması fft dağılımını düzeltir mi?

Üçüncüsü, loss hesabını matlabda bir rutin halinde 2 farklı yolla yazdım. Workspace attığım Vds ve Ids dalga verilerini çarpıp, zero hold yöntemini baz alarak (delta t ne ise onunla çarparak) tüm datalar üzerinde toplayıp frekansla çarptım. 2. yol ise simulinkte bu iki fonksiyonu direkt çarpıp power datasını çekerek oldu. Çektiğim değerleri toplayıp time arrayde kaç eleman varsa o sayıya bölerek average buldum. İki yöntem de aynı sonucu verdi. Sormak istediğim şu: 1 cycle için (50 Hz) buradaki hesaplar 3 ohm gibi düşük bir değerveriyor. Realistik mi? Ne eklemem gerekir? Vds, I ds ten elde edilen power hem swtiching, hem diode vb. hepsini kapsıyor mu?

Bu haftalık bunlar ^^

**Comment by mesutto** [comment]
Sampling time teorik bir konu değil, gerçek hayatta olan bir şey de değil zaten. Bizi tek ilgilendiren kısmı yeterince küçük olması (en iyi pratik anahtarlama frekansının 100 katında almak). Senin yaptığın doğru 👍

Gözlemin ve yorumun doğru, bir dalgayı yeterince sık örneklemezsen (bkz: nyquist frequency and aliasing) gördüğün frekans bileşenleri tam doğru olmaz. başka frekanslar üzerinde toplanırlar.

mf aslında doğrudan anahtarlama frekansı ile ilişkili (mf = fsw/fo, fo=fundamental frekans). Burada mf'in iki etkisi var: 1. mf ne kadar yüksekse harmonik frekansları o kadar ileri atılıyor (spektrumda sağa kayıyor). 2. harmoniklerin tepeleri düşüyor. Bu nedenle mf arttıkça harmoniklerin hem boyları azalıyor, hem de frekansları arttığı için pasif elemanlarca daha kolay süzülebiliyorlar (inductor, capacitor). Dün de konuştuğumuz gibi, dezavantaj ise loss'ların artması oluyor. Bu nedenle harmonikler ile loss'lar arasında bir ters orantı var ve mf'in ikisini de memnun edecek şekilde seçilmesi gerek.

mf overmodulation'a yol açmaz. ma yol açar. Lineer bölge (0<ma<1)'nin dışına çıkarsan, yani ma>1 olursa overmodulation olur ve low order harmonikler (3,5,7 gibi) görmeye başlarız. Bu SPWM'e özgü bir şey. SVPWM buna çare olabilir. bu konuda Hakan'a danışabilirsin.

Loss'ta adım adım gidelim. Önce integral almadan formülde yerine koyup (approximate formüller) çıkan sonuçlara bakarsan, doğruluğunu daha kolay gözlemlersin.

Vds eğer simulink'in verdiği ise yanlıştır. Çünkü orada gerçekçi bir model yok. Bu nedenle integral alırken datasheet verilerini kullanacağız. Vds'i ona göre hesaplattıracağız (veya direk P=I'2Rds yapacağız). Loss işini bugün toplantıda konuşuruz.

Eline sağlık, inverter işini neredeyse tamamen çözdün :) İstersen loss'lar ile birlikte harmonikler, akım gerilim ripple'ları ve bunların hesaplanması gibi konulara da girebiliriz. Dediğim gibi, harmonik ve loss güç elektroniğinin iki temel endeksi. Hangi converter'ı tasarlarsan tasarla (AC/DC, DC/DC, DC/AC farketmez) bu ikisi karşına çıkacak.
