### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by MelisaSarici** [MelisaSarici/GaN-FET#5]
@mesutto 

Merhaba hocam, 
Benim için takibinin kolay olması ve sizi de aynı sorularla sık sık rahatsız etmemek adına, Google Dökümanlardaki gibi izleyebileceğim bir yol haritası (milestonelar halinde) çıkarabilir misiniz?

Teşekkür ederim ^^

**Comment by mesutto** [comment]
Selam,

Hemen bakıyorum :)

**Comment by mesutto** [comment]
2 tane açtım, bi bak bakalım. Tarihleri salladım, sen kendine göre ayarlayabilirsin.

**Comment by mesutto** [comment]
Olabildiğince açıklamaya çalıştım ama yine de yüzyüze görüşürsek iyi olur, bi üstünden geçeriz.
