### ISSUE TITLE
Milestone 1 Reviewed

### ISSUE THREAD

**Issue by MelisaSarici** [MelisaSarici/GaN-FET#8]
@mesutto @furkankarakaya 
If I am not mistaken this time, I used the specified power, voltage and pf to derive the current to be drawn from the load. While doing this, I considered that the given power is 3 phase and for a reference power, I took pf as 0.9, meaning that my load is inductive since it is a motor and it needs 100e3*pf active power all the time. This power will be constant at all times, when power factor changes, Ic=Ip will change accordingly (right?)
With these assumptions at hand, first I found the operating point: Ic since all graphs were drawn wrt to Ic. Then derived the Eon, Eoff, trr etc from there. Then using the calculations provided in the module datasheet, I calculated the loss. It was 892 W. This is the result of 6 times per IGBT loss formulas. I thought that during one cycle, 5kHz, for one phase two IGBT will turn on and off. Similarly other phases will too (only different in on off duration-the flat  peaks of square waves I mean-) so 6*PperIgbt.

Is there anything wrong?

**Comment by furkankarakaya** [comment]
Melisa merhaba, Türkçe devam etmem de sorun yoktur umarım.
Evet power sabit çünkü yüke bağlı ve power factor değiştikçe Line-to-Line gerilimin sabit olduğu için yük akımının büyüklüğü değişmeli.  Senin de belirttiğin gibi akımına göre grafikten Eon ve Eoff'u seçmelisin. Toplam kayıpta dediğin gibi tek bir IGBT kaybının 6 katı olmalı.
